# Generated by Django 5.2.3 on 2025-06-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('budget', models.IntegerField()),
                ('timeline', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_status', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('proposed_title', models.CharField(max_length=255)),
                ('proposed_description', models.TextField()),
                ('estimated_cost', models.CharField(max_length=100)),
                ('implementation_time', models.CharField(max_length=100)),
                ('next_step', models.TextField()),
                ('generated_email', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='ai_model.inputlead')),
            ],
        ),
    ]
