# Generated by Django 5.2.3 on 2025-06-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadoutput',
            old_name='generated_email',
            new_name='budget_summary',
        ),
        migrations.RenameField(
            model_name='leadoutput',
            old_name='next_step',
            new_name='project_summary',
        ),
        migrations.RenameField(
            model_name='leadoutput',
            old_name='estimated_cost',
            new_name='recommended_budget',
        ),
        migrations.RenameField(
            model_name='leadoutput',
            old_name='implementation_time',
            new_name='recommended_duration',
        ),
        migrations.RenameField(
            model_name='leadoutput',
            old_name='proposed_description',
            new_name='timeline_summary',
        ),
        migrations.RemoveField(
            model_name='leadoutput',
            name='proposed_title',
        ),
        migrations.RemoveField(
            model_name='leadoutput',
            name='qualification_status',
        ),
        migrations.RemoveField(
            model_name='leadoutput',
            name='reason',
        ),
        migrations.AddField(
            model_name='leadoutput',
            name='task_breakdown',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
