# Generated by Django 5.2.3 on 2025-07-16 03:19

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='image/', verbose_name='img')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(verbose_name='title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Imge',
                'verbose_name_plural': 'Imges',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='name')),
                ('link', models.URLField(verbose_name='link')),
                ('logoimg', models.ImageField(upload_to='logo_img/', verbose_name='logo img')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'NewsLetter',
                'verbose_name_plural': 'NewsLetters',
            },
        ),
        migrations.CreateModel(
            name='OurResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('before_img', models.ImageField(upload_to='before_img/', verbose_name='before img')),
                ('after_img', models.ImageField(upload_to='after_img/', verbose_name='after img')),
                ('after_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='after description')),
                ('before_descrition', django_ckeditor_5.fields.CKEditor5Field(verbose_name='before descrition')),
            ],
            options={
                'verbose_name': 'Our Result',
                'verbose_name_plural': 'Our Results',
            },
        ),
        migrations.CreateModel(
            name='OurSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='text')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='answer')),
            ],
            options={
                'verbose_name': 'Our Solution',
                'verbose_name_plural': 'Our Solutions',
            },
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='name')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('rightcolor', models.CharField(max_length=50, verbose_name='right color')),
                ('leftcolor', models.CharField(max_length=50, verbose_name='left color')),
                ('link', models.URLField(verbose_name='link')),
                ('main_img', models.ImageField(upload_to='main_img/', verbose_name='main img')),
                ('right_img', models.ImageField(upload_to='right_img/', verbose_name='right img')),
                ('left_img', models.ImageField(upload_to='left_img/', verbose_name='left img')),
            ],
            options={
                'verbose_name': 'OurWork',
                'verbose_name_plural': 'OurWorks',
            },
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='name')),
                ('position', django_ckeditor_5.fields.CKEditor5Field(verbose_name='position')),
                ('whoimg', models.ImageField(upload_to='who_img/', verbose_name='who img')),
            ],
            options={
                'verbose_name': 'WhoWeAre',
                'verbose_name_plural': 'WhoWeAre',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='name')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('main_img', models.ImageField(upload_to='main_img/', verbose_name='main img')),
                ('logo', models.ImageField(upload_to='right_img/', verbose_name='logo img')),
                ('problem_defination', django_ckeditor_5.fields.CKEditor5Field(verbose_name='problem defination')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('imges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='products.imgs', verbose_name='imgs')),
                ('our_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='products.ourresults', verbose_name='our results')),
                ('our_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='products.oursolution', verbose_name='our solution')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='oursolution',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.projects', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='ourresults',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.projects', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='imgs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.projects', verbose_name='Project'),
        ),
    ]
