# Generated by Django 5.2.3 on 2025-07-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgs',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ourresults',
            name='project',
        ),
        migrations.RemoveField(
            model_name='oursolution',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='imges',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='our_results',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='our_solution',
        ),
        migrations.AddField(
            model_name='projects',
            name='imges',
            field=models.ManyToManyField(related_name='projects', to='products.imgs', verbose_name='imgs'),
        ),
        migrations.AddField(
            model_name='projects',
            name='our_results',
            field=models.ManyToManyField(related_name='projects', to='products.ourresults', verbose_name='our results'),
        ),
        migrations.AddField(
            model_name='projects',
            name='our_solution',
            field=models.ManyToManyField(related_name='projects', to='products.oursolution', verbose_name='our solution'),
        ),
    ]
