# Generated by Django 5.2.3 on 2025-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_imgs_project_remove_ourresults_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='right_img/', verbose_name='logo img'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='main_img/', verbose_name='main img'),
        ),
    ]
