# Generated by Django 5.2.3 on 2025-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_projects_logo_alter_projects_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='logo',
            field=models.ImageField(default='default_logo.jpg', upload_to='right_img/', verbose_name='logo img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='main_img',
            field=models.ImageField(default='default_logo.jpg', upload_to='main_img/', verbose_name='main img'),
            preserve_default=False,
        ),
    ]
