# Generated by Django 5.2.3 on 2025-07-26 11:30

import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_projects_logo_alter_projects_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_numbers', models.PositiveIntegerField(verbose_name='startup_numbers')),
                ('startup_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='startup_description')),
                ('strategies_numbers', models.PositiveIntegerField(verbose_name='strategies_numbers')),
                ('strategies_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='strategies_description')),
                ('subscribbers_numbers', models.PositiveIntegerField(verbose_name='subscribbers_numbers')),
                ('subscribbers_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='subscribbers_description')),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counters',
            },
        ),
        migrations.CreateModel(
            name='HomepageProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='name')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('subdescription', django_ckeditor_5.fields.CKEditor5Field(verbose_name='subdescription ')),
                ('main_img', models.ImageField(upload_to='main_img/', verbose_name='main img')),
                ('logo', models.ImageField(upload_to='logo_img/', verbose_name='logo img')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Homepage Project',
                'verbose_name_plural': 'Homepage Projects',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='services name')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
